import assert from 'node:assert/strict';
import {GameEngine,GameSession,fits,validState} from './game-modules.mjs';
const e=new GameEngine();e.start('chess');
assert.equal(e.act({type:'chess',from:'e2',to:'e4'},1,true),false,'Black cannot move White');
assert.equal(e.act({type:'chess',from:'e2',to:'e5'},0,true),false,'illegal move rejected');
for(const [from,to,side] of [['f2','f3',0],['e7','e5',1],['g2','g4',0],['d8','h4',1]])assert.ok(e.act({type:'chess',from,to},side,true));
assert.match(e.state.result,/checkmate/);assert.ok(validState(e.snapshot()));
assert.equal(e.act({type:'chess',from:'e2',to:'e4'},0,true),false);
e.start('chess');
for(const [from,to] of [['e2','e4'],['e7','e5'],['g1','f3'],['b8','c6'],['f1','c4'],['g8','f6'],['e1','g1']])assert.ok(e.act({type:'chess',from,to},0,false));
assert.match(e.state.fen.split(' ')[0],/RNBQ1RK1$/,'castling moves king and rook');
e.start('chess');e.chess.load('7k/P7/8/8/8/8/8/7K w - - 0 1');e.chessState();
assert.ok(e.act({type:'chess',from:'a7',to:'a8',promotion:'n'},0,true));assert.equal(e.chess.get('a8').type,'n');
e.start('chess');
for(const [from,to] of [['e2','e4'],['a7','a6'],['e4','e5'],['d7','d5'],['e5','d6']])assert.ok(e.act({type:'chess',from,to},0,false));
assert.equal(e.chess.get('d5'),undefined,'en passant removes the captured pawn');
e.start('noughts');
for(const [cell,side] of [[0,0],[3,1],[1,0],[4,1],[2,0]])assert.ok(e.act({type:'mark',cell},side,true));
assert.match(e.state.result,/Amber.*wins/);assert.equal(e.act({type:'mark',cell:8},1,true),false);
e.start('blocks');let b=e.state.blocks;
b.cells.fill(1,190);b.cells[194]=0;b.cells[195]=0;b.shape=1;b.x=3;b.y=18;
assert.ok(fits(b));assert.ok(e.act({type:'block',move:'drop',piece:0},0,true));assert.equal(b.lines,1);assert.equal(b.piece,1);
assert.equal(e.act({type:'block',move:'left',piece:0},1,true),false,'delayed input cannot move the next piece');
e.act({type:'block',move:'pause',piece:1},1,true);const y=b.y;assert.equal(e.tick(),false);assert.equal(b.y,y);
e.act({type:'block',move:'pause',piece:1},0,true);assert.ok(e.tick());
assert.ok(validState(e.snapshot()));assert.equal(validState({...e.snapshot(),blocks:{...b,cells:[-1]}}),false);
console.log('PASS: chess legality, turns, checkmate, castling; tic-tac-toe wins; block rows, stale inputs, and pause');
const host=new GameSession(),guest=new GameSession();let toHost=[],toGuest=[];
host.connect(true,m=>toGuest.push(structuredClone(m)));guest.connect(false,m=>toHost.push(structuredClone(m)));
function deliver(){for(const m of toHost.splice(0))host.receive(m);for(const m of toGuest.splice(0))guest.receive(m);}
host.pulse();deliver();guest.action({type:'mode',mode:'noughts'});
toHost=[];guest.pulse();deliver(); // Drop first command, retry delivers it.
assert.equal(host.getSnapshot().game.mode,'noughts');assert.deepEqual(guest.getSnapshot().game,host.getSnapshot().game);
host.action({type:'mark',cell:0});deliver();guest.action({type:'mark',cell:4});const duplicate=structuredClone(toHost[0]);deliver();
host.receive(duplicate);assert.equal(host.getSnapshot().game.revision,2,'a repeated command applies only once');
assert.deepEqual(guest.getSnapshot().game,host.getSnapshot().game);
host.action({type:'mode',mode:'chess'});toGuest=[];host.pulse();deliver();assert.equal(guest.getSnapshot().game.mode,'chess','snapshot loss heals without move history');
host.reset();guest.reset();host.pulse();deliver();assert.equal(guest.getSnapshot().game.mode,'draw');
assert.equal(JSON.stringify(host.getSnapshot()).includes('fen'),false,'clear removes game state');
console.log('PASS: encrypted-channel game protocol retries inputs, deduplicates, repairs lost snapshots, and clears rounds');
